### ISSUE TITLE
Asking for the TELECO dataset.

### ISSUE THREAD

**Issue by tangqideng** [GastonGarciaGonzalez/DC-VAE#2]
Hello,
I have encountered difficulties in uploading information and downloading the dataset from your webpage at https://iie.fing.edu.uy/investigacion/grupos/anomalias/en/telco-dataset-2/downloads/. I am a doctoral candidate from the National University of Defense Technology in China, primarily engaged in the study of deep learning and time-series analysis. I have recently developed a new model for time-series anomaly detection and wish to test its efficacy on your dataset. I have noted that you have provided labels for the training set, which resolves the issue of noise present in the existing datasets. I greatly admire your work and am eager to obtain the dataset for further research. Would you be able to send the dataset and labels to my email address: tqd18907@nudt.edu.cn? Thank you for your kindly support.
Name: Qideng Tang
Email: tqd18907@nudt.edu.cn
Subject: deep learning and time series analysis
Purpose: Research

**Comment by GastonGarciaGonzalez** [comment]
Hello, Qideng

Thanks for your message. Another option for downloading the dataset is through IEEE Dataport, where you can find it under the name TELCO. A subscription is required to download, but it's completely free.

**Comment by tangqideng** [comment]
Thanks for your help!!
